name: muex_flutter
version: 0.5.0
description: Flutter Widgets and helpers for the muex package.
author: Diego Covarrubias <dcov@pm.me>
homepage: https://github.com/dcov/muex

environment:
  sdk: '>=2.6.0-dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  muex:
    git:
      url: git://github.com/dcov/muex.git
      path: muex

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0

  mockito: ^4.1.1

  muex_gen:
    git:
      url: git://github.com/dcov/muex.git
      path: muex_gen
