name: muex_gen
version: 0.5.0
description: Code generator for the muex package.
author: Diego Covarrubias <dcov@pm.me>
homepage: https://github.com/dcov/muex

publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  analyzer: ^0.41.2

  build: ^1.6.2

  muex:
    git:
      url: git://github.com/dcov/muex.git
      ref: nnbd_migration
      path: muex

  source_gen: ^0.9.10

dev_dependencies:
  build_test: ^1.3.6
  build_runner: ^1.11.1
  logging: ^1.0.0
  test: ^1.15.7
