name: muex_gen
version: 0.5.0
description: Code generator for the muex package.
author: Diego Covarrubias <dcov@pm.me>
homepage: https://github.com/dcov/muex

environment:
  sdk: ">=2.6.0-dev <3.0.0"

dependencies:
  analyzer: ^0.39.17

  build: ^1.3.0

  muex:
    git:
      url: git://github.com/dcov/muex.git
      path: muex

  source_gen: ^0.9.5

dev_dependencies:
  build_test: ^1.2.0

  build_runner: ^1.10.0

  logging: ^0.11.4

  test: ^1.15.2
