name: muex_gen
version: 0.5.2
description: Code generator for the muex package.
author: Diego Covarrubias <dcov@pm.me>
homepage: https://github.com/dcov/muex

publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  analyzer: ^2.7.0

  build: ^2.1.1

  muex:
    git:
      url: git://github.com/dcov/muex.git
      ref: main
      path: muex

  source_gen: ^1.1.1

dev_dependencies:
  build_test: ^2.1.4
  build_runner: ^2.1.4
  logging: ^1.0.2
  test: ^1.19.2
