name: muex
version: 0.5.0
description: A composable state management solution.
author: Diego Covarrubias <dcov@pm.me>
homepage: https://github.com/dcov/muex

environment:
  sdk: '>=2.6.0-dev <3.0.0'

dependencies:
  meta: ^1.1.8
  quiver: ^2.1.3

dev_dependencies:
  mockito: ^4.1.1
  test: ^1.15.2
