name: muex
version: 0.5.1
description: A composable state management library.
author: Diego Covarrubias <dcov@pm.me>
homepage: https://github.com/dcov/muex

publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.7.0
  quiver: ^3.0.1

dev_dependencies:
  build_runner: ^2.1.4
  mockito: ^5.0.16
  test: ^1.19.2
